[
  [
    {
      hasMoved: false,
      stringType: "r",
      numericType: null,
      color: "b",
      moveHistory: [],
      legalMoves: [],
      position: { x: 0, y: 0, UCI: "a8" },
    },
    {
      hasMoved: false,
      stringType: "n",
      numericType: null,
      color: "b",
      moveHistory: [],
      legalMoves: [],
      position: { x: 1, y: 0, UCI: "b8" },
    },
    {
      hasMoved: false,
      stringType: "b",
      numericType: null,
      color: "b",
      moveHistory: [],
      legalMoves: [],
      position: { x: 2, y: 0, UCI: "c8" },
    },
    {
      hasMoved: false,
      stringType: "q",
      numericType: null,
      color: "b",
      moveHistory: [],
      legalMoves: [],
      position: { x: 3, y: 0, UCI: "d8" },
    },
    {
      hasMoved: false,
      stringType: "k",
      numericType: null,
      color: "b",
      moveHistory: [],
      legalMoves: [],
      position: { x: 4, y: 0, UCI: "e8" },
    },
    {
      hasMoved: false,
      stringType: "b",
      numericType: null,
      color: "b",
      moveHistory: [],
      legalMoves: [],
      position: { x: 5, y: 0, UCI: "f8" },
    },
    {
      hasMoved: false,
      stringType: "n",
      numericType: null,
      color: "b",
      moveHistory: [],
      legalMoves: [],
      position: { x: 6, y: 0, UCI: "g8" },
    },
    {
      hasMoved: false,
      stringType: "r",
      numericType: null,
      color: "b",
      moveHistory: [],
      legalMoves: [],
      position: { x: 7, y: 0, UCI: "h8" },
    },
  ],
  [
    {
      hasMoved: false,
      stringType: "p",
      numericType: null,
      color: "b",
      moveHistory: [],
      legalMoves: [],
      position: { x: 0, y: 1, UCI: "a7" },
    },
    {
      hasMoved: false,
      stringType: "p",
      numericType: null,
      color: "b",
      moveHistory: [],
      legalMoves: [],
      position: { x: 1, y: 1, UCI: "b7" },
    },
    {
      hasMoved: false,
      stringType: "p",
      numericType: null,
      color: "b",
      moveHistory: [],
      legalMoves: [],
      position: { x: 2, y: 1, UCI: "c7" },
    },
    {
      hasMoved: false,
      stringType: "p",
      numericType: null,
      color: "b",
      moveHistory: [],
      legalMoves: [],
      position: { x: 3, y: 1, UCI: "d7" },
    },

    {
      hasMoved: false,
      stringType: "p",
      numericType: null,
      color: "b",
      moveHistory: [],
      legalMoves: [],
      position: { x: 4, y: 1, UCI: "e7" },
    },
    {
      hasMoved: false,
      stringType: "p",
      numericType: null,
      color: "b",
      moveHistory: [],
      legalMoves: [],
      position: { x: 5, y: 1, UCI: "f7" },
    },
    {
      hasMoved: false,
      stringType: "p",
      numericType: null,
      color: "b",
      moveHistory: [],
      legalMoves: [],
      position: { x: 6, y: 1, UCI: "g7" },
    },
    {
      hasMoved: false,
      stringType: "p",
      numericType: null,
      color: "b",
      moveHistory: [],
      legalMoves: [],
      position: { x: 7, y: 1, UCI: "h7" },
    },
  ],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null],
  [
    {
      hasMoved: false,
      stringType: "p",
      numericType: null,
      color: "w",
      moveHistory: [],
      legalMoves: [
        { x: 0, y: 2, UCI: "a3" },
        { x: 0, y: 3, UCI: "a4" },
      ],
      position: { x: 0, y: 6, UCI: "a2" },
    },
    {
      hasMoved: false,
      stringType: "p",
      numericType: null,
      color: "w",
      moveHistory: [],
      legalMoves: [
        { x: 1, y: 2, UCI: "b3" },
        { x: 1, y: 3, UCI: "b4" },
      ],
      position: { x: 1, y: 6, UCI: "b2" },
    },
    {
      hasMoved: false,
      stringType: "p",
      numericType: null,
      color: "w",
      moveHistory: [],
      legalMoves: [
        { x: 2, y: 2, UCI: "c3" },
        { x: 2, y: 3, UCI: "c4" },
      ],
      position: { x: 2, y: 6, UCI: "c2" },
    },
    {
      hasMoved: false,
      stringType: "p",
      numericType: null,
      color: "w",
      moveHistory: [],
      legalMoves: [
        { x: 3, y: 2, UCI: "d3" },
        { x: 3, y: 3, UCI: "d4" },
      ],
      position: { x: 3, y: 6, UCI: "d2" },
    },
    {
      hasMoved: false,
      stringType: "p",
      numericType: null,
      color: "w",
      moveHistory: [],
      legalMoves: [
        { x: 4, y: 2, UCI: "e3" },
        { x: 4, y: 3, UCI: "e4" },
      ],
      position: { x: 4, y: 6, UCI: "e2" },
    },
    {
      hasMoved: false,
      stringType: "p",
      numericType: null,
      color: "w",
      moveHistory: [],
      legalMoves: [
        { x: 5, y: 2, UCI: "f3" },
        { x: 5, y: 3, UCI: "f4" },
      ],
      position: { x: 5, y: 6, UCI: "f2" },
    },
    {
      hasMoved: false,
      stringType: "p",
      numericType: null,
      color: "w",
      moveHistory: [],
      legalMoves: [
        { x: 6, y: 2, UCI: "g3" },
        { x: 6, y: 3, UCI: "g4" },
      ],
      position: { x: 6, y: 6, UCI: "g2" },
    },
    {
      hasMoved: false,
      stringType: "p",
      numericType: null,
      color: "w",
      moveHistory: [],
      legalMoves: [
        { x: 7, y: 2, UCI: "h3" },
        { x: 7, y: 3, UCI: "h4" },
      ],
      position: { x: 7, y: 6, UCI: "h2" },
    },
  ],
  [
    {
      hasMoved: false,
      stringType: "r",
      numericType: null,
      color: "w",
      moveHistory: [],
      legalMoves: [],
      position: { x: 0, y: 7, UCI: "a1" },
    },
    {
      hasMoved: false,
      stringType: "n",
      numericType: null,
      color: "w",
      moveHistory: [],
      legalMoves: [],
      position: { x: 1, y: 7, UCI: "b1" },
    },
    {
      hasMoved: false,
      stringType: "b",
      numericType: null,
      color: "w",
      moveHistory: [],
      legalMoves: [],
      position: { x: 2, y: 7, UCI: "c1" },
    },
    {
      hasMoved: false,
      stringType: "q",
      numericType: null,
      color: "w",
      moveHistory: [],
      legalMoves: [],
      position: { x: 3, y: 7, UCI: "d1" },
    },
    {
      hasMoved: false,
      stringType: "k",
      numericType: null,
      color: "w",
      moveHistory: [],
      legalMoves: [],
      position: { x: 4, y: 7, UCI: "e1" },
    },
    {
      hasMoved: false,
      stringType: "b",
      numericType: null,
      color: "w",
      moveHistory: [],
      legalMoves: [],
      position: { x: 5, y: 7, UCI: "f1" },
    },
    {
      hasMoved: false,
      stringType: "n",
      numericType: null,
      color: "w",
      moveHistory: [],
      legalMoves: [],
      position: { x: 6, y: 7, UCI: "g1" },
    },
    {
      hasMoved: false,
      stringType: "r",
      numericType: null,
      color: "w",
      moveHistory: [],
      legalMoves: [],
      position: { x: 7, y: 7, UCI: "h1" },
    },
  ],
];
